### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by cyber-cliff** [jclerc/xmusic#1]
hi, i just want to ask on how to install this? I tried on my centos. But i cant run it.

Thanks.

**Comment by jclerc** [comment]
On bottom of [README.md](https://github.com/JClerc/XMusic/blob/master/README.md) you should have a section **Getting started**.

But if you have just a 500 internal error without anything else, it's maybe because you aren't on localhost, so you need a production config but it is not defined by default.
So you just need to:
1. Delete `app/config/production.php` file
2. Duplicate `app/config/development.php` file
3. Copy new file to `app/config/production.php`
